### Mohamad Ibnu Fajar Maulana
### 21083010106
### DATA WRANGLING C

### SOAL
##### Dengan menggunakan data kedua matriks (matriks A dan B) yang degenerate acak pada Array Operations, lakukan penambahan, perkalian, pembagian, 3*A-2*B, tambahkan 100 pada  scalar matriks A, A dipangkatkan 3, dan akar pangkat dari A

In [1]:
import numpy as np

# definisikan matriks A dan B dengan ukuran 3x3
A = np.array([[22, 8, 10], [12, 21, 4], [7, 21, 9]])
B = np.array([[8, 9, 10], [31, 44, 47], [2, 5, 20]])

# penjumlahan matriks
penjumlahan = np.add(A, B)
print('\033[1m', '\33[32m')
print("Hasil penjumlahan matriks A dan B:")
print(penjumlahan)

# perkalian matriks
perkalian = np.matmul(A, B)
print('\033[1m', '\33[33m')
print("Hasil perkalian matriks A dan B:")
print(perkalian)

# pembagian matriks
pembagian = np.divide(A, B)
print('\033[1m', '\33[34m')
print("Hasil pembagian matriks A dan B:")
print(pembagian)

# 3A-2B
operasi = np.subtract(np.multiply(3, A), np.multiply(2, B))
print('\033[1m', '\33[35m')
print("Hasil operasi 3A-2B:")
print(operasi)

# tambahkan 100 pada scalar matriks A
skalar = np.add(A, 100)
print('\033[1m', '\33[36m')
print("Hasil penambahan 100 pada skalar matriks A:")
print(skalar)

# A dipangkatkan 3
pangkat = np.power(A, 3)
print('\033[1m', '\33[31m')
print("Hasil pemangkatan matriks A dengan pangkat 3:")
print(pangkat)

# akar pangkat dari A
akar = np.sqrt(A)
print('\033[1m', '\33[32m')
print("Hasil akar pangkat 2 dari matriks A:")
print(akar)

 
Hasil penjumlahan matriks A dan B:
[[30 17 20]
 [43 65 51]
 [ 9 26 29]]
 
Hasil perkalian matriks A dan B:
[[ 444  600  796]
 [ 755 1052 1187]
 [ 725 1032 1237]]
 
Hasil pembagian matriks A dan B:
[[2.75       0.88888889 1.        ]
 [0.38709677 0.47727273 0.08510638]
 [3.5        4.2        0.45      ]]
 
Hasil operasi 3A-2B:
[[ 50   6  10]
 [-26 -25 -82]
 [ 17  53 -13]]
 
Hasil penambahan 100 pada skalar matriks A:
[[122 108 110]
 [112 121 104]
 [107 121 109]]
 
Hasil pemangkatan matriks A dengan pangkat 3:
[[10648   512  1000]
 [ 1728  9261    64]
 [  343  9261   729]]
 
Hasil akar pangkat 2 dari matriks A:
[[4.69041576 2.82842712 3.16227766]
 [3.46410162 4.58257569 2.        ]
 [2.64575131 4.58257569 3.        ]]
